services:
  # Serviço 1: O Banco de Dados PostgreSQL
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: mvp_user
      POSTGRES_PASSWORD: mvp_pass
      POSTGRES_DB: mvp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço 2: A nossa API Python
  api:
    build: ./backend  # Constrói a imagem a partir da pasta 'backend'
    ports:
      - "5000:5000"
    environment:
      # A URL de conexão aponta para o serviço 'db', não 'localhost'
      - DATABASE_URL=postgresql://mvp_user:mvp_pass@db:5432/mvp_db
    depends_on:
      - db # Diz à API para esperar o banco de dados iniciar primeiro

volumes:
  postgres_data: